# Generated by Django 3.2.8 on 2021-10-08 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAutores',
            fields=[
                ('id_autor', models.SmallIntegerField(db_column='ID_autor', primary_key=True, serialize=False)),
                ('nome_autor', models.CharField(blank=True, max_length=50, null=True)),
                ('sobrenome_autor', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'tbl_autores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblEditoras',
            fields=[
                ('id_editora', models.SmallAutoField(db_column='ID_editora', primary_key=True, serialize=False)),
                ('nome_editora', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_editoras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblImagefield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'imageupload',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblLivro',
            fields=[
                ('id_livro', models.SmallAutoField(db_column='ID_livro', primary_key=True, serialize=False)),
                ('nome_livro', models.CharField(max_length=50)),
                ('isbn', models.IntegerField(db_column='ISBN')),
                ('data_pub', models.DateField()),
                ('preco_livro', models.DecimalField(decimal_places=0, max_digits=10)),
                ('id_autor', models.ForeignKey(db_column='ID_autor', on_delete=django.db.models.deletion.DO_NOTHING, to='api_biblioteca.tblautores')),
                ('id_editora', models.ForeignKey(db_column='ID_editora', on_delete=django.db.models.deletion.DO_NOTHING, to='api_biblioteca.tbleditoras')),
            ],
            options={
                'db_table': 'tbl_livro',
                'managed': True,
            },
        ),
    ]
